### ISSUE TITLE
How to integrate a debugger into the IDE 2.0 

### ISSUE THREAD

**Issue by felias-fogg** [DeqingSun/unoDebugTestPackage#1]
Hi,

I have also worked on building a debugger for AVR chips (classic ATtinys and ATmegaX8) and came up with a quite stable version, which works on an UNO or similar board: https://github.com/felias-fogg/dw-link. So far, however, I have been unable to integrate it into the Arduino IDE 2. I have tried your version, but was unsuccessful. Does your solution still work with the current IDE version? And if so, can you give me some clues how to proceed.

Best regards,
Bernhard

**Comment by DeqingSun** [comment]
I haven't touch it for a long time so some info may be out of date. I'll double check this week to see if the board support still work because I will teach it again this fall. I can confirm it worked last fall with newest IDE.

1. check the txt files in https://github.com/DeqingSun/unoDebugTestPackage/tree/main/avr8debug and that is how to enable debug function for your board.

2. Then the Arduino IDE will treat your program as OpenOCD. At least when I did it, the Arduino will call openocd with fixed parameters. 

https://github.com/arduino/arduino-ide/issues/87#issuecomment-792354558 

So I need to do a dirty trick in my program to replace the parameters if they match the Arduino pattern.

https://github.com/DeqingSun/dwire-debug/commit/973be694ca0f3c9fc1f31f87be4df8577ed0220f

**Comment by DeqingSun** [comment]
Some update. The current repo does not work with Arduino 2.2.4 due to an updated version of marus25.cortex-debug-1.5.1.

There are 2 updates need to be made:

[The updated openOCD parameter](https://github.com/Marus/cortex-debug/blob/eba74258010ee73b3848d2862d1b885d55e4fe43/src/openocd.ts#L169) is different from the old one so your tool need be able to detect the new one.

[The updated openOCD detection regex](https://github.com/Marus/cortex-debug/blob/eba74258010ee73b3848d2862d1b885d55e4fe43/src/openocd.ts#L222) and your tool must print something like "Info : Listening on port 50000 for gdb connection" for cortex-debug to move forward.

**Comment by felias-fogg** [comment]
Hi Deqing,

thanks a lot! Now it works! But it would be, of course, much nicer to have a less "hacked" version. Any idea how to approach that?

Cheers,
Bernhard

**Comment by DeqingSun** [comment]
I saw your post on Arduino forum about the custom json file. I think that can be an option to make it less hacky, at the cost of adding a json to every project. My target users are students so I personally would prefer to leave the hard work to me.

I don't think there is perfect solution because the debug plugin is for arm gdb and openocd. And frankly speaking, it is written with a lot of options hardcoded. So mimicking the arm toolchain with avr ones will involves some hacks.
